# Generated by Django 3.2.13 on 2024-08-09 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20240802_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Consultorio')),
                ('address', models.CharField(max_length=250, verbose_name='Direccion')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Diagnostico')),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='FichaKinesica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.diagnostico')),
            ],
            options={
                'verbose_name': 'Ficha kinesica',
                'verbose_name_plural': 'Fichas kinesicas',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Localidad')),
                ('codigo_postal', models.CharField(max_length=6, verbose_name='Codigo Postal')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='MedicoDerivante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Medico derivante')),
            ],
            options={
                'verbose_name': 'Medico derivante',
                'verbose_name_plural': 'Medicos derivantes',
            },
        ),
        migrations.CreateModel(
            name='Obra_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Obra Social')),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obra Sociales',
            },
        ),
        migrations.CreateModel(
            name='OrdenDeConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_needed', models.IntegerField(verbose_name='Sesiones totales')),
                ('sessions_done', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sesiones hechas')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalizacion')),
                ('state', models.CharField(blank=True, choices=[('EN PROGRESO', 'En Progreso'), ('PRESENTADO', 'Presentado'), ('COBRADO', 'Cobrado')], max_length=100, null=True, verbose_name='Estado')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Horario')),
                ('kinesic_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.fichakinesica')),
            ],
            options={
                'verbose_name': 'Orden de consulta',
                'verbose_name_plural': 'Ordenes de consulta',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('state', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Realizado'), (3, 'Cancelado'), (4, 'Falto')], verbose_name='Estado')),
                ('consult_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.ordendeconsulta')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('matricula', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido')),
                ('address', models.CharField(max_length=200, verbose_name='Direccion')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Telefono')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.localidad')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.AddField(
            model_name='fichakinesica',
            name='medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.medicoderivante'),
        ),
        migrations.AddField(
            model_name='fichakinesica',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patients',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patients.localidad'),
        ),
        migrations.AddField(
            model_name='patients',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patients.obra_social'),
        ),
    ]
